services:
  db:
    image: postgres:17
    container_name: nestjs-chat-db
    ports:
      - "5432:5432"
    volumes:
      - "db-data:/var/lib/postgresql/data"
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-esgi}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-esgi}
      POSTGRES_DB: ${POSTGRES_DB:-esgi}
    restart: unless-stopped

  adminer:
    image: adminer
    container_name: nestjs-chat-adminer
    ports:
      - "8080:8080"
    environment:
      ADMINER_DESIGN: pepa-linha

  minio:
    image: quay.io/minio/minio
    container_name: nestjs-chat-minio
    command: 'server /data --console-address ":9001"'
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - "minio-data:/data"
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER:-minioadmin}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD:-minioadmin}

volumes:
  db-data:
  minio-data:
